// Created by iWeb 2.0.4 local-build-20121218

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,22),url:'broadening_perspectives_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'broadening_perspectives_files/stroke_1.png'},{rect:new IWRect(1,-1,257,2),url:'broadening_perspectives_files/stroke_2.png'},{rect:new IWRect(258,-1,2,2),url:'broadening_perspectives_files/stroke_3.png'},{rect:new IWRect(258,1,2,22),url:'broadening_perspectives_files/stroke_4.png'},{rect:new IWRect(258,23,2,2),url:'broadening_perspectives_files/stroke_5.png'},{rect:new IWRect(1,23,257,2),url:'broadening_perspectives_files/stroke_6.png'},{rect:new IWRect(-1,23,2,2),url:'broadening_perspectives_files/stroke_7.png'}],new IWSize(259,24))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('broadening_perspectives_files/broadening_perspectivesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
